minify: true
darkmode: true
language_switcher: true
cache:
  enable: false
favicon:
  small: https://img.njzjz.win/?url=avatars2.githubusercontent.com/u/9496702?s=460&v=4
  medium: https://img.njzjz.win/?url=avatars2.githubusercontent.com/u/9496702?s=460&v=4
  apple_touch_icon: https://img.njzjz.win/?url=avatars2.githubusercontent.com/u/9496702?s=460&v=4
  safari_pinned_tab: https://img.njzjz.win/?url=avatars2.githubusercontent.com/u/9496702?s=460&v=4
footer:
  since: 2016
  icon:
    animated: true
creative_commons:
  sidebar: true
  post: true
scheme: Gemini
menu:
  home: / || fa fa-home
  cv: /cv/ || fas fa-file
  softwares: /softwares/ || fab fa-app-store
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
menu_settings:
  badges: true
avatar:
  url: https://img.njzjz.win/?url=avatars2.githubusercontent.com/u/9496702?s=460&v=4
social:
  GitHub: https://github.com/njzjz || fab fa-github
  E-Mail: mailto:jinzhe.zeng@rutgers.edu || fa fa-envelope
  ORCID: https://orcid.org/0000-0002-1515-8172 || fab fa-orcid
  Scholar: https://scholar.google.com/citations?user=P7gRtg4AAAAJ || fab fa-google
  ResearchGate: https://www.researchgate.net/profile/Jinzhe_Zeng || fab fa-researchgate
  Twitter: https://twitter.com/njzjz || fab fa-twitter
  Zhihu: https://www.zhihu.com/people/zeng-jin-zhe || fab fa-zhihu
  Weibo: https://weibo.com/njzjz || fab fa-weibo
follow_me:
  Twitter: https://twitter.com/njzjz || twitter
  WeChat: https://img.njzjz.win/?url=open.weixin.qq.com/qr/code?username=gh_c3cec7062858 || wechat
reward_settings:
  enable: true
  animation: true
reward:
  wechatpay: https://img.njzjz.win/?url=i.loli.net/2018/08/26/5b821ce3a2497.jpg
  alipay: https://img.njzjz.win/?url=i.loli.net/2018/08/26/5b821c8f752b4.png
related_posts:
   enable: false
post_edit:
  enable: true
  url: https://github.com/njzjz/njzjz.github.io/tree/hexo/source/ # Link for view source.
codeblock:
  copy_button:
    enable: true
    show_result: true
reading_progress:
  enable: true
bookmark:
  enable: true
github_banner:
  enable: true
  permalink: https://github.com/njzjz/njzjz.github.io
seo: true
index_with_subtitle: true
exturl: true
math:
  enable: true
valine:
  enable: true
  appid: YMI6904uVYbYEvp2Q0MtJc8n-MdYXbMMI
  appkey: hY1CYIauaeAmQe75EmPUFgN0
  notify: true
  visitor: true
  recordIP: true
  enableQQ: true
  serverURLs: https://blogcomment.njzjz.win
google_analytics:
  tracking_id: UA-74033886-1
local_search:
  enable: true
pdf:
  enable: true
links_settings:
  icon: fa fa-link
  title: Friend Links
  layout: block
links:
  "Darrin York Group": http://theory.rutgers.edu/profile.php?people_id=230
  "Tong Zhu Group": https://computchem.cn/people
  "hexi blog": https://hexi519.github.io
vendors:
  anime: //js.njzjz.win/npm/animejs@3.2.0/lib/anime.min.js
  fontawesome: //js.njzjz.win/npm/@fortawesome/fontawesome-free@5/css/all.min.css
  mathjax: //js.njzjz.win/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  mhchem: //js.njzjz.win/npm/mathjax-mhchem@3
  katex: //js.njzjz.win/npm/katex@0/dist/katex.min.css
  copy_tex_js: //js.njzjz.win/npm/katex@0/dist/contrib/copy-tex.min.js
  pjax: //js.njzjz.win/gh/theme-next/theme-next-pjax@0/pjax.min.js
  jquery: //js.njzjz.win/npm/jquery@3/dist/jquery.min.js
  fancybox: //js.njzjz.win/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
  fancybox_css: //js.njzjz.win/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css
  mediumzoom: //js.njzjz.win/npm/medium-zoom@1/dist/medium-zoom.min.js
  lazyload: //js.njzjz.win/npm/lozad@1/dist/lozad.min.js
  pangu: //js.njzjz.win/npm/pangu@4/dist/browser/pangu.min.js
  quicklink: //js.njzjz.win/npm/quicklink@1/dist/quicklink.umd.js
  disqusjs_js: //js.njzjz.win/npm/disqusjs@1/dist/disqus.js
  disqusjs_css: //js.njzjz.win/npm/disqusjs@1/dist/disqusjs.css
  valine: //js.njzjz.win/npm/valine@1/dist/Valine.min.js
  gitalk_js: //js.njzjz.win/npm/gitalk@1/dist/gitalk.min.js
  gitalk_css: //js.njzjz.win/npm/gitalk@1/dist/gitalk.css
  algolia_instant_js: //js.njzjz.win/npm/instantsearch.js@2/dist/instantsearch.min.js
  algolia_instant_css: //js.njzjz.win/npm/instantsearch.js@2/dist/instantsearch.min.css
  pdfobject: //js.njzjz.win/npm/pdfobject@2/pdfobject.min.js
  mermaid: //js.njzjz.win/npm/mermaid@8/dist/mermaid.min.js
  velocity: //js.njzjz.win/npm/velocity-animate@1/velocity.min.js
  velocity_ui: //js.njzjz.win/npm/velocity-animate@1/velocity.ui.min.js
  pace: //js.njzjz.win/npm/pace-js@1/pace.min.js
  pace_css: //js.njzjz.win/npm/pace-js@1/themes/blue/pace-theme-minimal.css
  canvas_nest: //js.njzjz.win/gh/theme-next/theme-next-canvas-nest@1/canvas-nest.min.js
  canvas_nest_nomobile: //js.njzjz.win/gh/theme-next/theme-next-canvas-nest@1/canvas-nest-nomobile.min.js
  canvas_ribbon: //js.njzjz.win/gh/theme-next/theme-next-canvas-ribbon@1/canvas-ribbon.js
