minify: true
darkmode: true
language_switcher: true
cache:
  enable: false
favicon:
  small: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@9d4d517f7c008456c8f13320ed78d70c6742f623/avatar.png
  medium: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@9d4d517f7c008456c8f13320ed78d70c6742f623/avatar.png
  apple_touch_icon: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@9d4d517f7c008456c8f13320ed78d70c6742f623/avatar.png
  safari_pinned_tab: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@9d4d517f7c008456c8f13320ed78d70c6742f623/avatar.png
footer:
  since: 2016
  icon:
    animated: true
creative_commons:
  sidebar: true
  post: true
scheme: Gemini
menu:
  home: / || fa fa-home
  cv: /cv/ || fas fa-file
  softwares: /softwares/ || fab fa-app-store
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
menu_settings:
  badges: true
avatar:
  url: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@9d4d517f7c008456c8f13320ed78d70c6742f623/avatar.png
social:
  GitHub: https://github.com/njzjz || fab fa-github
  E-Mail: mailto:jinzhe.zeng@rutgers.edu || fa fa-envelope
  ORCID: https://orcid.org/0000-0002-1515-8172 || fab fa-orcid
  Scholar: https://scholar.google.com/citations?user=P7gRtg4AAAAJ || fab fa-google
  ResearchGate: https://www.researchgate.net/profile/Jinzhe_Zeng || fab fa-researchgate
  Twitter: https://twitter.com/njzjz || fab fa-twitter
  Zhihu: https://www.zhihu.com/people/zeng-jin-zhe || fab fa-zhihu
  Weibo: https://weibo.com/njzjz || fab fa-weibo
follow_me:
  Twitter: https://twitter.com/njzjz || twitter
  WeChat: https://img.njzjz.win/?url=open.weixin.qq.com/qr/code?username=gh_c3cec7062858 || wechat
reward_settings:
  enable: true
  animation: true
mobile_layout_economy: true
pjax: false
lazyload: true
mediumzoom: true
pangu: true
quicklink:
  enable: true
  home: true
  archive: true
motion:
  enable: false
  async: true
reward:
  wechatpay: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@5471f41503354e524e431315d03f44379260c2a0/wechatpay.png
  alipay: https://cdn.jsdelivr.net/gh/njzjz/njzjz.github.io@5471f41503354e524e431315d03f44379260c2a0/alipay.png
related_posts:
   enable: true
post_edit:
  enable: true
  url: https://github.com/njzjz/njzjz.github.io/tree/hexo/source/ # Link for view source.
note:
  style: modern
  icons: true
codeblock:
  copy_button:
    enable: true
    show_result: true
reading_progress:
  enable: true
bookmark:
  enable: true
github_banner:
  enable: true
  permalink: https://github.com/njzjz/njzjz.github.io
seo: true
index_with_subtitle: true
exturl: true
baidu_push: false
math:
  mathjax:
    enable: true
comments:
  lazyload: true
disqusjs:
  enable: false
  api: https://njzjz.win/api/
  apikey: 2BQ7XHnqBr57WPaTp2ozSwhwTJ7k5gOvwA9ruq9OE8vEZSQ43YYFNa8UjL1t62Ls
  shortname: njzjz
waline:
  enable: true
  serverURL: https://comment.njzjz.win
  vistor: true
busuanzi_count:
  enable: false
google_analytics:
  tracking_id: UA-74033886-1
  only_pageview: true
local_search:
  enable: true
pdf:
  enable: true
links_settings:
  icon: fa fa-link
  title: Friend Links
  layout: block
links:
  "Darrin York Group": http://theory.rutgers.edu/profile.php?people_id=230
  "Tong Zhu Group": https://computchem.cn/people
  "hexi blog": https://hexi519.github.io
vendors:
  internal: jsdelivr
  plugins: jsdelivr
nprogress:
  enable: true
preconnect: true
custom_file_path:
  style: source/_data/styles.styl
